version: "3.1"

services:
  mongo:
    container_name: gaw-mongo
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
    
  mongo-init:
    container_name: gaw-mongo-init
    build: ./mongo-init
    links:
      - mongo
      
  mongo-client:
    container_name: gaw-mongo-client
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo

  go-agile-web:
    container_name: gaw-app
    #image: go-agile-web/app.goagile.web
    build: ./api
    ports:
    - 8080:8080
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  app:
    image: 'io.kaplab.cards.webapp.image'
    build: './app'
    ports:
        - 3000:80
